### PR TITLE
Italian locale update

### PR DESCRIPTION
**Pull request by ghost**
Locale files reviewed and updated where necessary, created if missing.

### CODE REVIEW

**Comment by ghost** [comment]
I've noticed that some new strings aren't present in the existing locale files, can you update them using a script or do they have to be manually added? Example: Acacia bush leaves, Brown coral, etc.

**Comment by Xanthin** [comment]
Wahh, sorry. I got no mail from Github about your messages (or about anything else). Sorry. 

I haven't used and looked for minetest the whole time, just now I was a little curious.
I guess there is **a lot** of new stuff in there now. 

And weren't there steps towards a more centralised, more official translation system for mods? I'm so not up to date atm. :laughing:

**Comment by ghost** [comment]
Oh don't worry: when I have opened this pull request I did not had a clear idea about the difference between v0.4.16 and v0.4.17-dev; there is no need to update your fork.

Those steps that you have mentioned will be implemented in v0.5, as far as I know. :)

**Comment by Xanthin** [comment]
Ah, okay, that sounds reasonable.

I too had some trouble until I understood what the master branch is used for now. :smile:

**Pull request closed without merging**
